Repository vaadin/flow-components, pull requests merged in 2021-06, with the labels that each got.

#1742 fix: update date picker overlay after setting I18N settings
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/DatePickerI18nPage.java
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/TestI18N.java
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerI18nIT.java
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
  vaadin-date-picker-flow-parent/vaadin-date-picker-testbench/pom.xml
  vaadin-date-picker-flow-parent/vaadin-date-picker-testbench/src/main/java/com/vaadin/flow/component/datepicker/testbench/DatePickerElement.java
Labels: target/14.6, target/14.7, target/19.0, target/20.0

#1762 chore: deprecate IronList in favor of VirtualList
  vaadin-iron-list-flow-parent/vaadin-iron-list-flow/src/main/java/com/vaadin/flow/component/ironlist/IronList.java
Labels: no-polymer

#1766 Chore: update settings for flow-maven-plugin
  pom.xml
  scripts/lib/versions.js
  scripts/templates/pom-integration-tests.xml
  vaadin-accordion-flow-parent/vaadin-accordion-flow-integration-tests/pom.xml
  vaadin-app-layout-flow-parent/vaadin-app-layout-flow-integration-tests/pom.xml
  vaadin-avatar-flow-parent/vaadin-avatar-flow-integration-tests/pom.xml
  vaadin-avatar-flow-parent/vaadin-avatar-flow/pom.xml
  vaadin-board-flow-parent/vaadin-board-flow-integration-tests/pom.xml
  vaadin-button-flow-parent/vaadin-button-flow-integration-tests/pom.xml
  vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/pom.xml
  vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/pom.xml
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/pom.xml
  vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/pom.xml
  vaadin-context-menu-flow-parent/vaadin-context-menu-flow-integration-tests/pom.xml
  vaadin-cookie-consent-flow-parent/vaadin-cookie-consent-flow-integration-tests/pom.xml
  vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/pom.xml
  vaadin-custom-field-flow-parent/vaadin-custom-field-flow-integration-tests/pom.xml
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/pom.xml
  vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/pom.xml
  vaadin-details-flow-parent/vaadin-details-flow-integration-tests/pom.xml
  vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/pom.xml
  vaadin-form-layout-flow-parent/vaadin-form-layout-flow-integration-tests/pom.xml
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/pom.xml
  vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/pom.xml
  vaadin-icons-flow-parent/vaadin-icons-flow-integration-tests/pom.xml
  vaadin-iron-list-flow-parent/vaadin-iron-list-flow-integration-tests/pom.xml
  vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/pom.xml
  vaadin-login-flow-parent/vaadin-login-flow-integration-tests/pom.xml
  vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/pom.xml
  vaadin-notification-flow-parent/vaadin-notification-flow-integration-tests/pom.xml
  vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow-integration-tests/pom.xml
  vaadin-progress-bar-flow-parent/vaadin-progress-bar-flow-integration-tests/pom.xml
  vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/pom.xml
  vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/pom.xml
  vaadin-select-flow-parent/vaadin-select-flow-integration-tests/pom.xml
  vaadin-split-layout-flow-parent/vaadin-split-layout-flow-integration-tests/pom.xml
  vaadin-tabs-flow-parent/vaadin-tabs-flow-integration-tests/pom.xml
  vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/pom.xml
  vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/pom.xml
  vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/pom.xml
Labels: cherry-picked-14.7

#1785 refactor: make Icon use <vaadin-icon> web component
  vaadin-icons-flow-parent/pom.xml
  vaadin-icons-flow-parent/vaadin-icons-flow-demo/pom.xml
  vaadin-icons-flow-parent/vaadin-icons-flow-integration-tests/pom.xml
  vaadin-icons-flow-parent/vaadin-icons-flow-integration-tests/src/main/java/com/vaadin/flow/component/icon/demo/IconView.java
  vaadin-icons-flow-parent/vaadin-icons-flow-integration-tests/src/test/java/com/vaadin/flow/component/icon/tests/IconIT.java
  vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/Icon.java
  vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/VaadinIcon.java
Labels: no-polymer

#1793 chore: deprecate IronIcon in favor of Icon
  vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/IronIcon.java
Labels: no-polymer

#1801 feat: suppress template warning
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/ComboBoxTest.java
  vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/main/java/com/vaadin/flow/component/contextmenu/ContextMenu.java
  vaadin-context-menu-flow-parent/vaadin-context-menu-flow/src/test/java/com/vaadin/flow/component/contextmenu/ContextMenuTest.java
  vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
  vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogTest.java
  vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/ColumnGroup.java
  vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
  vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridColumnGroupTest.java
  vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridColumnTest.java
  vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridTest.java
  vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java
  vaadin-notification-flow-parent/vaadin-notification-flow/src/test/java/com/vaadin/flow/component/notification/NotificationTest.java
  vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
  vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectTest.java
  vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/main/java/com/vaadin/flow/component/virtuallist/VirtualList.java
  vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/test/java/com/vaadin/flow/component/virtuallist/tests/VirtualListTest.java
Labels: no-polymer

#1795 feat: deprecate setHeightByRows in favor of setAllRowsVisible in Grid
  vaadin-grid-flow-parent/vaadin-grid-flow-demo/src/main/java/com/vaadin/flow/component/grid/demo/GridDemo.java
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/ColumnResizeEventPage.java
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridSingleSelectionPage.java
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridView.java
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/RecalculateColumnWidthsPage.java
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridInitialExpandPage.java
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewIT.java
  vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
  vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridTest.java
Labels: target/14.7

#1813 chore: remove normalization of deprecated icons
  vaadin-icons-flow-parent/vaadin-icons-flow-integration-tests/src/test/java/com/vaadin/flow/component/icon/tests/IconIT.java
  vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/Icon.java
Labels: no-polymer

#1814 perf: remove the unnecessary span wrapper from virtual list items
  vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow-integration-tests/src/test/java/com/vaadin/flow/component/virtuallist/tests/VirtualListIT.java
  vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow/src/main/java/com/vaadin/flow/component/virtuallist/VirtualList.java
Labels: no-polymer

#1820 test: fix usage of selenium hub in pro components
  vaadin-accordion-flow-parent/vaadin-accordion-flow-integration-tests/src/test/java/com/vaadin/flow/component/accordion/test/AbstractParallelTest.java
  vaadin-accordion-flow-parent/vaadin-accordion-flow-integration-tests/src/test/java/com/vaadin/flow/component/accordion/test/BasicUseIT.java
  vaadin-accordion-flow-parent/vaadin-accordion-flow-integration-tests/src/test/java/com/vaadin/flow/component/accordion/test/TemplateSupportIT.java
  vaadin-app-layout-flow-parent/vaadin-app-layout-flow-integration-tests/src/test/java/com/vaadin/flow/component/applayout/test/AbstractParallelTest.java
  vaadin-app-layout-flow-parent/vaadin-app-layout-flow-integration-tests/src/test/java/com/vaadin/flow/component/applayout/test/AppLayoutIT.java
  vaadin-board-flow-parent/vaadin-board-flow-integration-tests/src/test/java/com/vaadin/flow/component/board/test/AbstractDemoIT.java
  vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/confirmdialog/test/AbstractParallelTest.java
  vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/confirmdialog/test/BasicUseIT.java
  vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/confirmdialog/test/DimensionsIT.java
  vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/confirmdialog/test/FeaturesDiyIT.java
  vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/confirmdialog/test/helpers/Actionwords.java
  vaadin-cookie-consent-flow-parent/vaadin-cookie-consent-flow-integration-tests/src/test/java/com/vaadin/flow/component/cookieconsent/AbstractParallelTest.java
  vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/src/test/java/com/vaadin/flow/component/crud/test/AbstractParallelTest.java
  vaadin-custom-field-flow-parent/vaadin-custom-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/customfield/test/AbstractParallelTest.java
  vaadin-custom-field-flow-parent/vaadin-custom-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/customfield/test/BasicIT.java
  vaadin-custom-field-flow-parent/vaadin-custom-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/customfield/test/ErrorIT.java
  vaadin-custom-field-flow-parent/vaadin-custom-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/customfield/test/NameFieldViewIT.java
  vaadin-details-flow-parent/vaadin-details-flow-integration-tests/src/test/java/com/vaadin/flow/component/details/test/AbstractParallelTest.java
  vaadin-details-flow-parent/vaadin-details-flow-integration-tests/src/test/java/com/vaadin/flow/component/details/test/BasicIT.java
  vaadin-flow-components-shared/src/main/java/com/vaadin/tests/AbstractParallelTest.java
  vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/test/AbstractParallelTest.java
  vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/test/BasicIT.java
  vaadin-login-flow-parent/vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/test/AbstractParallelTest.java
  vaadin-login-flow-parent/vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/test/BasicIT.java
  vaadin-login-flow-parent/vaadin-login-flow-integration-tests/src/test/java/com/vaadin/flow/component/login/test/I18nIT.java
  vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/test/java/com/vaadin/flow/component/richtexteditor/test/AbstractParallelTest.java
Labels: target/20.0

#1817 docs: add hint about using setSplitterPosition with vertical orientation
  vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java
Labels: target/14.6, target/14.7, target/20.0

#1826 test: fix mistake in expression `||` must be `&&`
  vaadin-flow-components-shared/src/main/java/com/vaadin/tests/AbstractParallelTest.java
Labels: target/20.0

#1827 test: fix using selenium hub in charts tests
  vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/AbstractTBTest.java
  vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/BasicChartIT.java
  vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ChartSizeIT.java
  vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ChartStyleIT.java
  vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ColumnWithLazyMultiLevelDrilldownCallbackTestsIT.java
  vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ColumnWithLazyMultiLevelDrilldownIT.java
  vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/DynamicChangesIT.java
  vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/DynamicChangingChartIT.java
  vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/DynamicExtremesIT.java
  vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/GlobalOptionsIT.java
  vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/PieWithoutAccessibilityIT.java
  vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ServerSideEventsIT.java
  vaadin-flow-components-shared/src/main/java/com/vaadin/tests/AbstractParallelTest.java
  vaadin-flow-components-shared/src/main/java/com/vaadin/tests/ComponentDemoTest.java
Labels: target/20.0

#1832 test: fix faky assertion that fails in certain docker containers
  vaadin-iron-list-flow-parent/vaadin-iron-list-flow-integration-tests/src/test/java/com/vaadin/flow/component/ironlist/tests/IronListIT.java
  vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow-integration-tests/src/test/java/com/vaadin/flow/component/virtuallist/tests/VirtualListIT.java
Labels: target/20.0

#1834 test: fix locale assertion in grid for JDK16 changes
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/AddingColumnsIT.java
  vaadin-iron-list-flow-parent/vaadin-iron-list-flow-integration-tests/src/test/java/com/vaadin/flow/component/ironlist/tests/IronListIT.java
  vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow-integration-tests/src/test/java/com/vaadin/flow/component/virtuallist/tests/VirtualListIT.java
Labels: target/20.0

#1840 refactor: use new methods instead of deprecated render() and update()
  vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/Chart.java
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/GeneratedVaadinComboBox.java
  vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/GeneratedVaadinNotification.java
  vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
  vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/generated/GeneratedVaadinSelect.java
Labels: no-polymer
