Repository vaadin/flow-components, pull requests merged in 2021-05, with the labels that each got.

#600 feat: allow setting the bean type after the Grid has been created
  vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
  vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/BeanGridTest.java
Labels: vaadin-grid

#865 fix: Ensure editor closing when page refreshed while using PreserveOnRefresh
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/PreserveOnRefreshPage.java
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/PreserveOnRefreshIT.java
  vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Labels: target/14.5, target/14.6, target/14.7, target/19.0, target/20.0

#895 chore: fix webjar updates for pro components [skip ci]
  scripts/updateWebjars.js
Labels: target/14.5, target/14.7

#468 fix: Prevent IllegalArgumentException when sortable columns are remov…
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/pom.xml
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/RemoveSortableColumnPage.java
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/RemoveSortableColumnsIT.java
  vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Labels: vaadin-grid

#876 fix: restore sorting indicators after column order change
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/SortingPage.java
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/SortingIT.java
  vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Labels: target/14.5, target/14.6, target/14.7, target/19.0, target/20.0

#927 fix: change how setSeries converts array to ArrayList
  vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/Configuration.java
  vaadin-charts-flow-parent/vaadin-charts-flow/src/test/java/com/vaadin/flow/component/charts/ConfigurationJSONSerializationTest.java
  vaadin-charts-flow-parent/vaadin-charts-flow/src/test/java/com/vaadin/flow/component/charts/ConfigurationTest.java
Labels: target/14.5, target/14.6, target/14.7, target/19.0, target/20.0

#942 docs: clarify use of setSeries for rendered chart
  vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/Configuration.java
Labels: target/14.5, target/14.6, target/14.7, target/19.0, target/20.0

#959 chore: fix package-name calculation by removing extra quotes
  pom.xml
Labels: target/19.0, target/20.0

#970 chore: fix icon and treegrid namespaces for OSGi bundle
  pom.xml
Labels: target/19.0, target/20.0

#973 fix: disable client side validation
  vaadin-select-flow-parent/vaadin-select-flow-integration-tests/pom.xml
  vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/main/java/com/vaadin/flow/component/select/examples/OverrideClientValidationPage.java
  vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/test/java/com/vaadin/flow/component/select/test/BasicFeaturesIT.java
  vaadin-select-flow-parent/vaadin-select-flow-integration-tests/src/test/java/com/vaadin/flow/component/select/test/OverrideClientValidationIT.java
  vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/FieldValidationUtil.java
  vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
  vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/generated/GeneratedVaadinSelect.java
Labels: target/14.6, target/14.7, target/19.0, target/20.0

#761 chore: add IT for dialog shortcut and writing
  vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/DialogWithShortcutPage.java
  vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogWithShortcutIT.java
Labels: target/14.6, target/14.7, target/19.0, target/20.0

#981 chore: update testbench 6.4.0
  pom.xml
Labels: target/14.7

#979 feat: add theme API to MessageListItem
  vaadin-messages-flow-parent/vaadin-messages-flow-integration-tests/src/main/java/com/vaadin/flow/component/messages/tests/MessageListPage.java
  vaadin-messages-flow-parent/vaadin-messages-flow-integration-tests/src/test/java/com/vaadin/flow/component/messages/tests/MessageListIT.java
  vaadin-messages-flow-parent/vaadin-messages-flow/src/main/java/com/vaadin/flow/component/messages/MessageListItem.java
  vaadin-messages-flow-parent/vaadin-messages-flow/src/test/java/com/vaadin/flow/component/messages/tests/MessageListTest.java
  vaadin-messages-flow-parent/vaadin-messages-testbench/src/main/java/com/vaadin/flow/component/messages/testbench/MessageElement.java
Labels: vaadin-messages

#1000 chore: add PR template [skip ci]
  PULL_REQUEST_TEMPLATE.md
Labels: internal

#1702 test: remove easymock usage
  vaadin-button-flow-parent/vaadin-button-flow/src/test/java/com/vaadin/flow/component/button/tests/ButtonTest.java
Labels: target/14.6, target/14.7, target/19.0, target/20.0

#998 test: fix mockito errors accessing protected API in JDK16
  package.json
  pom.xml
  vaadin-app-layout-flow-parent/vaadin-app-layout-flow/pom.xml
  vaadin-board-flow-parent/vaadin-board-flow/pom.xml
  vaadin-charts-flow-parent/vaadin-charts-flow/pom.xml
  vaadin-checkbox-flow-parent/vaadin-checkbox-flow/pom.xml
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow/pom.xml
  vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/pom.xml
  vaadin-context-menu-flow-parent/vaadin-context-menu-flow/pom.xml
  vaadin-crud-flow-parent/vaadin-crud-flow/pom.xml
  vaadin-custom-field-flow-parent/vaadin-custom-field-flow/pom.xml
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow/pom.xml
  vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/pom.xml
  vaadin-details-flow-parent/vaadin-details-flow/pom.xml
  vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogWithShortcutIT.java
  vaadin-dialog-flow-parent/vaadin-dialog-flow/pom.xml
  vaadin-form-layout-flow-parent/vaadin-form-layout-flow/pom.xml
  vaadin-grid-flow-parent/vaadin-grid-flow/pom.xml
  vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/GridMultiSelectionModelTest.java
  vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/pom.xml
  vaadin-list-box-flow-parent/vaadin-list-box-flow/pom.xml
  vaadin-login-flow-parent/vaadin-login-flow/pom.xml
  vaadin-radio-button-flow-parent/vaadin-radio-button-flow/pom.xml
  vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/pom.xml
  vaadin-select-flow-parent/vaadin-select-flow/pom.xml
  vaadin-text-field-flow-parent/vaadin-text-field-flow/pom.xml
  vaadin-time-picker-flow-parent/vaadin-time-picker-flow/pom.xml
  vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/pom.xml
Labels: target/14.6, target/14.7, target/19.0, target/20.0

#994 fix: Disable checkbox after applying value
  vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/main/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupDisabledItemPage.java
  vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupDisabledItemIT.java
  vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java
Labels: target/14.6, target/14.7, target/19.0, target/20.0

#1699 documentation: Add note to RadioButtonGroup#setRendered JavaDoc
  vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
Labels: target/14.6, target/14.7, target/19.0, target/20.0
