Repository vaadin/flow-components, pull requests merged in 2021-03, with the labels that each got.

#687 chore: replace the hard coded branch version [skip-ci]
  scripts/prepareDeploy.sh
Labels: target/14.4, target/14.5, target/18.0, target/19.0

#694 chore:fix version setting brings in wrong snapshot [skip-ci]
  scripts/prepareDeploy.sh
Labels: target/19.0, target/master

#724 chore: exit build properly when error found in annotation [skip-ci]
  scripts/lib/versions.js
Labels: target/14.4, target/14.5, target/18.0, target/19.0

#725 fix: make dialog scoped shortcuts work
  vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/DialogWithShortcutPage.java
  vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/dialog/tests/DialogWithShortcutIT.java
  vaadin-dialog-flow-parent/vaadin-dialog-flow/src/main/java/com/vaadin/flow/component/dialog/Dialog.java
  vaadin-dialog-flow-parent/vaadin-dialog-flow/src/test/java/com/vaadin/flow/component/dialog/DialogTest.java
Labels: target/14.5, target/19.0

#756 chore: fix the cherry-pick bot
  scripts/cherryPick.js
Labels: target/14.5, target/14.6, target/18.0
