Repository vaadin/flow-components, pull requests merged in 2021-04, with the labels that each got.

#787 chore: update repo name in the cherry-pick bot
  scripts/cherryPick.js
Labels: cherry-picked-14.5, cherry-picked-14.6, cherry-picked-19.0

#804 chore: fix build script after repo renaming [skip ci]
  scripts/build.sh
  scripts/prepareDeploy.sh
Labels: target/14.5, target/14.6, target/19.0

#773 fix: move clear from rebuild to correct places
  vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/listbox/test/ListBoxRetainValuePage.java
  vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/listbox/test/ListBoxRetainValueIT.java
  vaadin-list-box-flow-parent/vaadin-list-box-flow/src/main/java/com/vaadin/flow/component/listbox/ListBoxBase.java
Labels: target/14.5, target/14.6, target/19.0, vaadin-list-box

#757 fix: make non-functioning clear() method in ComboBoxElement work
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/ComboBoxClearPage.java
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ComboBoxClearIT.java
  vaadin-combo-box-flow-parent/vaadin-combo-box-testbench/src/main/java/com/vaadin/flow/component/combobox/testbench/ComboBoxElement.java
Labels: vaadin-combo-box

#778 fix: adds explicit fetching of initial page when autoOpen is false on opening.
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/LazyComboBoxFilterPage.java
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyComboBoxFilterIT.java
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBox.java
Labels: vaadin-combo-box

#825 chore: cache versions to increase npm updater performance [skip ci]
  scripts/lib/versions.js
  scripts/updateNpmVer.js
Labels: target/14.5, target/14.6, target/19.0

#834 test: remove npmpackage annotation with wrong vers
  vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/dialog/tests/DialogWithShortcutPage.java
Labels: target/14.6

#167 fix: set locale in onAttach instead of constructor
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/test/java/com/vaadin/flow/component/datepicker/DatePickerSerializableTest.java
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/test/java/com/vaadin/flow/component/datepicker/DatePickerTest.java
Labels: vaadin-date-picker

#844 doc: update documentation with formatting conventions [skip ci]
  README.md
Labels: target/14.6, target/14.7, target/19.0, target/20.0

#855 chore: do not format html files, fix dom-modules
  pom.xml
  vaadin-charts-flow-parent/vaadin-charts-flow-demo/src/main/java/com/vaadin/flow/component/charts/examples/combinations/ColumnLineAndPie.html
  vaadin-charts-flow-parent/vaadin-charts-flow-demo/src/main/java/com/vaadin/flow/component/charts/examples/combinations/MultipleAxes.html
  vaadin-charts-flow-parent/vaadin-charts-flow-demo/src/main/java/com/vaadin/flow/component/charts/examples/lineandscatter/BasicLineWithCallouts.html
  vaadin-charts-flow-parent/vaadin-charts-flow-demo/src/main/java/com/vaadin/flow/component/charts/examples/lineandscatter/Scatter.html
  vaadin-charts-flow-parent/vaadin-charts-flow-demo/src/main/java/com/vaadin/flow/component/charts/examples/other/BoxPlot.html
  vaadin-charts-flow-parent/vaadin-charts-flow-demo/src/main/java/com/vaadin/flow/component/charts/examples/other/ColorThreshold.html
  vaadin-charts-flow-parent/vaadin-charts-flow-demo/src/main/java/com/vaadin/flow/component/charts/examples/other/Gauge.html
  vaadin-charts-flow-parent/vaadin-charts-flow-demo/src/main/java/com/vaadin/flow/component/charts/examples/other/GaugeWithDualAxes.html
  vaadin-charts-flow-parent/vaadin-charts-flow-demo/src/main/java/com/vaadin/flow/component/charts/examples/other/SolidGauge.html
  vaadin-charts-flow-parent/vaadin-charts-flow-demo/src/main/java/com/vaadin/flow/component/charts/examples/other/Spiderweb.html
  vaadin-charts-flow-parent/vaadin-charts-flow-demo/src/main/java/com/vaadin/flow/component/charts/examples/other/WaterfallChart.html
  vaadin-charts-flow-parent/vaadin-charts-flow-demo/src/main/java/com/vaadin/flow/component/charts/examples/timeline/CompareMultipleSeries.html
Labels: target/14.6, target/14.7, target/19.0, target/20.0

#846 fix: synchronize column width recalculation with data refresh
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/RecalculateColumnWidthsPage.java
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/RecalculateColumnWidthsIT.java
  vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Labels: target/14.5, target/14.6, target/14.7, target/19.0, target/20.0
