Repository vaadin/flow-components, pull requests merged in 2021-07, with the labels that each got.

#1856 chore: allow passing hub ip as parameter [skip-ci]
  scripts/build.sh
Labels: target/14.6, target/14.7, target/20.0

#1861 fix: run package before jetty:run
  README.md
  scripts/run.sh
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/benchmark/run-benchmark.js
Labels: target/14.6, target/14.7, target/20.0

#1869 chore: allow passing quiet flag as parameter [skip ci]
  scripts/build.sh
Labels: target/14.6, target/14.7, target/20.0

#1906 fix: allow partial I18N instances for Upload
  vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/FileBufferView.java
  vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/NonImmediateUploadView.java
  vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/UploadI18nView.java
  vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/UploadTestsI18N.java
  vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/UploadView.java
  vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/it/UploadView.java
  vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/UploadI18nIT.java
  vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/UploadIT.java
  vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java
Labels: target/20.0

#1929 chore: add quotes to test stament to avoid random syntax errors [skip ci]
  scripts/run.sh
Labels: target/14.6, target/14.7, target/20.0, target/21.0

#1907 feat: allow providing custom FileFactory to FileBuffer, MultiFileBuffer
  vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/FileBuffer.java
  vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/receivers/MultiFileBuffer.java
Labels: target/20.0, target/21.0

#1938 Fix: make axisRescaled null safe
  vaadin-charts-flow-parent/vaadin-charts-flow-demo/src/main/java/com/vaadin/flow/component/charts/demo/examples/dynamic/DynamicExtremes.java
  vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/DynamicExtremesIT.java
  vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/ProxyChangeForwarder.java
Labels: target/14.6, target/14.7, target/20.0, target/21.0

#1953 chore: Test pinned version of selenium/standalone-chrome [skip ci]
  scripts/build.sh
Labels: target/14.6, target/14.7, target/20.0, target/21.0
