Repository vaadin/flow-components, pull requests merged in 2021-09, with the labels that each got.

#2107 chore: ensure the correct overlay is used when multiple selects are open
  vaadin-select-flow-parent/vaadin-select-testbench/src/main/java/com/vaadin/flow/component/select/testbench/SelectElement.java
Labels: target/20.0, target/14.7, target/21.0, target/14.8

#2106 Trim the text before selecting to be more compatible with templates
  vaadin-select-flow-parent/vaadin-select-testbench/src/main/java/com/vaadin/flow/component/select/testbench/SelectElement.java
Labels: target/20.0, target/14.7, target/21.0, target/14.8

#2118 chore: no vaadin prefix in repo name [skip ci]
  scripts/generateChangeLog.js
Labels: target/14.6, target/20.0, target/14.7, target/21.0, target/14.8

#2099 fix: prevent duplicate value changed events from DateTimePicker.setValue
  vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePickerPage.java
  vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePickerStepPage.java
  vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePickerValueChangePage.java
  vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datetimepicker/DateTimePickerIT.java
  vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datetimepicker/DateTimePickerStepIT.java
  vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datetimepicker/DateTimePickerValueChangeIT.java
  vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
  vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/test/java/com/vaadin/flow/component/datetimepicker/DateTimePickerTest.java
  vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-testbench/src/main/java/com/vaadin/flow/component/datetimepicker/testbench/DateTimePickerElement.java
  vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/StepsUtil.java
  vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
Labels: target/20.0, target/14.7, target/21.0, target/14.8

#2136 chore:add vaadin-dev-server dependency
  pom.xml
  vaadin-accordion-flow-parent/vaadin-accordion-flow-integration-tests/pom.xml
  vaadin-app-layout-flow-parent/vaadin-app-layout-flow-integration-tests/pom.xml
  vaadin-avatar-flow-parent/vaadin-avatar-flow-integration-tests/pom.xml
  vaadin-board-flow-parent/vaadin-board-flow-integration-tests/pom.xml
  vaadin-button-flow-parent/vaadin-button-flow-integration-tests/pom.xml
  vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/pom.xml
  vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/pom.xml
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/pom.xml
  vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/pom.xml
  vaadin-context-menu-flow-parent/vaadin-context-menu-flow-integration-tests/pom.xml
  vaadin-cookie-consent-flow-parent/vaadin-cookie-consent-flow-integration-tests/pom.xml
  vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/pom.xml
  vaadin-custom-field-flow-parent/vaadin-custom-field-flow-integration-tests/pom.xml
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/pom.xml
  vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/pom.xml
  vaadin-details-flow-parent/vaadin-details-flow-integration-tests/pom.xml
  vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/pom.xml
  vaadin-form-layout-flow-parent/vaadin-form-layout-flow-integration-tests/pom.xml
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/pom.xml
  vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/pom.xml
  vaadin-icons-flow-parent/vaadin-icons-flow-integration-tests/pom.xml
  vaadin-iron-list-flow-parent/vaadin-iron-list-flow-integration-tests/pom.xml
  vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/pom.xml
  vaadin-login-flow-parent/vaadin-login-flow-integration-tests/pom.xml
  vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow-integration-tests/pom.xml
  vaadin-material-theme-flow-parent/vaadin-material-theme-flow-integration-tests/pom.xml
  vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/pom.xml
  vaadin-messages-flow-parent/vaadin-messages-flow-integration-tests/pom.xml
  vaadin-notification-flow-parent/vaadin-notification-flow-integration-tests/pom.xml
  vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow-integration-tests/pom.xml
  vaadin-progress-bar-flow-parent/vaadin-progress-bar-flow-integration-tests/pom.xml
  vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/pom.xml
  vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/pom.xml
  vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/pom.xml
  vaadin-select-flow-parent/vaadin-select-flow-integration-tests/pom.xml
  vaadin-split-layout-flow-parent/vaadin-split-layout-flow-integration-tests/pom.xml
  vaadin-tabs-flow-parent/vaadin-tabs-flow-integration-tests/pom.xml
  vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/pom.xml
  vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/pom.xml
  vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/pom.xml
  vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow-integration-tests/pom.xml
Labels: target/21.0

#2141 chore: improve flaky ServerSideEventsIT (CP: 22)
  vaadin-charts-flow-parent/vaadin-charts-flow-demo/src/main/java/com/vaadin/flow/component/charts/demo/examples/dynamic/ServerSideEvents.java
  vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ServerSideEventsIT.java
Labels: target/21.0

#2140 chore: improve flaky ServerSideEventsIT
  vaadin-charts-flow-parent/vaadin-charts-flow-demo/src/main/java/com/vaadin/flow/component/charts/examples/dynamic/ServerSideEvents.java
  vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/src/test/java/com/vaadin/flow/component/charts/tests/ServerSideEventsIT.java
Labels: target/14.8

#2165 fix: make DateTimePicker apply initial steps
  vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePickerStepPage.java
  vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datetimepicker/DateTimePickerStepIT.java
  vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
Labels: target/20.0, target/14.7, target/21.0, target/14.8
