Repository vaadin/flow-components, pull requests merged in 2021-02, with the labels that each got.

#601 Chore: fix the deploy script to filter keywords [skip ci]
  scripts/prepareDeploy.sh
Labels: target/14.5

#596 chore: stop the cherry-pick properly [skip ci]
  scripts/cherryPick.js
Labels: target/14.4, target/14.5, target/18.0

#604 chore: fix grep [skip ci]
  scripts/prepareDeploy.sh
Labels: target/14.5

#595 chore: remove redundant 'V' from release note [skip ci]
  scripts/generateChangeLog.js
Labels: target/14.4, target/14.5, target/18.0

#611 feat: allow custom plugins in pom modules
  scripts/templates/pom-flow-pro.xml
  scripts/templates/pom-flow.xml
  scripts/updateJavaPOMs.js
  vaadin-accordion-flow-parent/vaadin-accordion-flow/pom.xml
  vaadin-app-layout-flow-parent/vaadin-app-layout-flow/pom.xml
  vaadin-avatar-flow-parent/vaadin-avatar-flow/pom.xml
  vaadin-board-flow-parent/vaadin-board-flow/pom.xml
  vaadin-button-flow-parent/vaadin-button-flow/pom.xml
  vaadin-charts-flow-parent/vaadin-charts-flow/pom.xml
  vaadin-checkbox-flow-parent/vaadin-checkbox-flow/pom.xml
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow/pom.xml
  vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/pom.xml
  vaadin-context-menu-flow-parent/vaadin-context-menu-flow/pom.xml
  vaadin-cookie-consent-flow-parent/vaadin-cookie-consent-flow/pom.xml
  vaadin-crud-flow-parent/vaadin-crud-flow/pom.xml
  vaadin-custom-field-flow-parent/vaadin-custom-field-flow/pom.xml
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow/pom.xml
  vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/pom.xml
  vaadin-details-flow-parent/vaadin-details-flow/pom.xml
  vaadin-dialog-flow-parent/vaadin-dialog-flow/pom.xml
  vaadin-form-layout-flow-parent/vaadin-form-layout-flow/pom.xml
  vaadin-grid-flow-parent/vaadin-grid-flow/pom.xml
  vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/pom.xml
  vaadin-icons-flow-parent/vaadin-icons-flow/pom.xml
  vaadin-iron-list-flow-parent/vaadin-iron-list-flow/pom.xml
  vaadin-list-box-flow-parent/vaadin-list-box-flow/pom.xml
  vaadin-login-flow-parent/vaadin-login-flow/pom.xml
  vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/pom.xml
  vaadin-notification-flow-parent/vaadin-notification-flow/pom.xml
  vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow/pom.xml
  vaadin-progress-bar-flow-parent/vaadin-progress-bar-flow/pom.xml
  vaadin-radio-button-flow-parent/vaadin-radio-button-flow/pom.xml
  vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/pom.xml
  vaadin-select-flow-parent/vaadin-select-flow/pom.xml
  vaadin-split-layout-flow-parent/vaadin-split-layout-flow/pom.xml
  vaadin-tabs-flow-parent/vaadin-tabs-flow/pom.xml
  vaadin-text-field-flow-parent/vaadin-text-field-flow/pom.xml
  vaadin-time-picker-flow-parent/vaadin-time-picker-flow/pom.xml
  vaadin-upload-flow-parent/vaadin-upload-flow/pom.xml
Labels: target/14.4, target/14.5, target/18.0

#623 chore: fix the update platform script [skip ci]
  scripts/updatePlatform.js
Labels: target/14.4, target/14.5, target/18.0

#559 test: fix and enable ComboBox switch to defined count test
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/dataview/ItemCountUnknownComboBoxIT.java
Labels: target/18.0

#637 Chore: post a comment if cherry pick failed [skip-ci]
  scripts/cherryPick.js
Labels: target/14.4, target/14.5, target/18.0

#638 Ignore generated directory in IT modules
  .gitignore
Labels: target/18.0

#645 test: lazy loading Grid shows items properly after filter apply
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridFilteringPage.java
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridFilteringIT.java
Labels: target/18.0, vaadin-grid

#652 Cherrypick: Added timeout between calls of when vaadin/vaadin-time-picker-flow#81 (14.5)
  vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/timepicker/tests/TimePickerPage.java
  vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerIT.java
  vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/resources/META-INF/resources/frontend/timepickerConnector.js
Labels: target/14.4

#661 chore: update script for V20.0
  scripts/prepareDeploy.sh
Labels: target/14.4, target/14.5, target/18.0, target/19.0

#657 chore: align the cherry-pick script with flow
  scripts/cherryPick.js
Labels: target/14.4, target/14.5, target/18.0, target/19.0

#677 chore: do not deliver any release with snapshot dependencies [skip-ci]
  scripts/prepareDeploy.sh
Labels: target/14.5, target/19.0
