Repository vaadin/flow-components, pull requests merged in 2022-01, with the labels that each got.

#2479 chore: fix build script
  scripts/build.sh
Labels: target/14.8

#2478 feat: implement HasEnabled interface in MenuBar
  vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/java/com/vaadin/flow/component/menubar/MenuBar.java
Labels: vaadin-menu-bar

#2540 fix: check sub cache queue of a grid instance in connector
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/treegrid/it/TreeGridDetachAttachPage.java
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/treegrid/it/TreeGridDetachAttachIT.java
  vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Labels: target/14.8, target/22.0

#2558 fix: only use custom label when setting HTML
  vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/frontend/inject-checkbox.js
  vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/InjectedCheckboxIT.java
  vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/Checkbox.java
Labels: target/22.0

#2529 fix: delete selected key when input is cleared
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ClearValueIT.java
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
Labels: target/22.0

#2578 fix: enforce checkbox web component disabled state
  vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/main/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupDisabledItemPage.java
  vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupDisabledItemIT.java
  vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java
Labels: target/14.8, target/22.0

#2582 test: scope grid benchmark styles
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/frontend/benchmark.js
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridBenchmark.java
Labels: target/14.8, target/22.0
