Repository vaadin/flow-components, pull requests merged in 2022-09, with the labels that each got.

#3689 fix: make map classes serializable
  vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/Assets.java
  vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Coordinate.java
  vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/Extent.java
  vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/configuration/style/Icon.java
  vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/events/FeatureEventDetails.java
  vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/serialization/MapSerializer.java
  vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/MapSerializableTest.java
Labels: target/23.1, target/23.2

#3758 fix: add missing contextMenuConnector import
  vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow/src/main/resources/META-INF/resources/frontend/menubarConnector.js
Labels: target/23.1, target/23.2

#3749 fix: prevent debouncer override in callback
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/LazyLoadingPage.java
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/LazyLoadingIT.java
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/resources/META-INF/resources/frontend/comboBoxConnector.js
Labels: target/23.1, target/23.2

#3750 chore: update date-fns to 2.29.1
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
Labels: target/22.0, target/23.1, target/23.2

#3777 chore: update date-dns to 2.29.3
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow/date-fns/package-lock.json
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow/date-fns/package.json
Labels: target/14.8

#3634 fix: handle possible null coordinates
  vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/events/MapClickEvent.java
  vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/events/MapEventUtil.java
  vaadin-map-flow-parent/vaadin-map-flow/src/main/java/com/vaadin/flow/component/map/events/MapViewMoveEndEvent.java
  vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/events/MapClickEventTest.java
  vaadin-map-flow-parent/vaadin-map-flow/src/test/java/com/vaadin/flow/component/map/events/MapViewMoveEndEventTest.java
Labels: target/23.2

#3786 fix: sort indicator order for append multi-sort priority
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridViewSortingIT.java
  vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Labels: target/23.2

#3787 fix: change the fetch query so that the filter is passed
  vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModel.java
  vaadin-grid-flow-parent/vaadin-grid-flow/src/test/java/com/vaadin/flow/component/grid/AbstractGridMultiSelectionModelTest.java
Labels: target/23.1, target/23.2

#3784 fix: keep opened state with preserve on refresh
  vaadin-notification-flow-parent/vaadin-notification-flow-integration-tests/src/main/java/com/vaadin/flow/component/notification/tests/PreserveOnRefreshPage.java
  vaadin-notification-flow-parent/vaadin-notification-flow-integration-tests/src/test/java/com/vaadin/flow/component/notification/tests/PreserveOnRefreshIT.java
  vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java
  vaadin-notification-flow-parent/vaadin-notification-flow/src/test/java/com/vaadin/flow/component/notification/NotificationTest.java
Labels: target/23.1, target/23.2

#3804 test: Make DataCommunicator clean old flush request
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/DetachedGridWithPreserveOnRefreshPage.java
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DetachedGridWithPreserveOnRefreshIT.java
Labels: target/14.8, target/22.0, target/23.1, target/23.2, target/14.9
