Repository vaadin/flow-components, pull requests merged in 2023-12, with the labels that each got.

#5798 fix: call to setSplitterPoisition on splitter-dragend event
  vaadin-split-layout-flow-parent/vaadin-split-layout-flow-integration-tests/src/test/java/com/vaadin/flow/component/splitlayout/tests/SplitterPositionIT.java
  vaadin-split-layout-flow-parent/vaadin-split-layout-flow/src/main/java/com/vaadin/flow/component/splitlayout/SplitLayout.java
Labels: target/23.3, target/24.1, target/24.2, target/23.4

#5832 fix: regex to get the version for computing [skip ci]
  scripts/generateChangeLog.js
Labels: target/main, target/22.0, target/14.10, target/24.2, target/23.4, target/24.3, target/22.1, target/14.11

#5855 chore: bump testbench to 8.2.5
  pom.xml
Labels: target/23.4

#5845 fix: Make request transient so it does not prevent serialization
  vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/treegrid/TreeGrid.java
Labels: target/23.3, target/24.1, target/24.2, target/23.4, target/24.3

#5853 fix: handle empty node id in component renderer
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/ComponentRendererPage.java
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/ComponentRendererIT.java
  vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/flow-component-renderer.js
Labels: target/23.3, target/24.0, target/24.1, target/24.2, target/23.4, target/24.3

#5879 chore: bump Testbench to 9.2.1 (#5875) (CP: 24.3)
  pom.xml
Labels: cherry-pick
