Repository vaadin/flow-components, pull requests merged in 2023-09, with the labels that each got.

#5413 fire the OpenedChangeEvent for the opened-changed dom event
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/main/java/com/vaadin/flow/component/datepicker/DatePickerViewDemoPage.java
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerIT.java
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
Labels: target/24.0, target/24.1

#5424 fix: set listenOn to make shortcuts work in ConfirmDialog
  vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/src/main/java/com/vaadin/flow/component/confirmdialog/tests/ShortcutsPage.java
  vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/src/test/java/com/vaadin/flow/component/confirmdialog/tests/ShortcutsIT.java
  vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow/src/main/java/com/vaadin/flow/component/confirmdialog/ConfirmDialog.java
Labels: target/23.3, target/24.0, target/24.1

#5457 fix: add opened property change listener for all Notification constructors
  vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java
  vaadin-notification-flow-parent/vaadin-notification-flow/src/test/java/com/vaadin/flow/component/notification/NotificationTest.java
Labels: target/24.1

#5466 fix: download new chromium before wtr run
  scripts/wtr.js
Labels: target/24.1

#5477 test: update DetachReattachIT to check for initial value
  vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/test/java/com/vaadin/flow/component/richtexteditor/tests/RichTextEditorDetachReattachIT.java
Labels: target/24.1

#5484 fix: ignore removed nodes in flow component directive
  vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/test/flow-component-renderer.test.ts
  vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/flow-component-directive.js
Labels: target/24.1

#5491 fix: properly clear pending requests on grid item collapse
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector-tree.test.ts
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/shared.ts
  vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.js
Labels: target/24.1

#5501 chore: Update TestBench version to 9.1.0.beta1
  pom.xml
Labels: target/24.2

#5506 fix: ignore ancestor enabled state in tabs internal logic
  vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/Tabs.java
  vaadin-tabs-flow-parent/vaadin-tabs-flow/src/test/java/com/vaadin/flow/component/tabs/tests/TabsTest.java
Labels: target/23.3, target/24.1, target/24.2

#5520 chore: Update TestBench to 9.1.0.beta2
  pom.xml
Labels: target/24.2
