Repository vaadin/flow-components, pull requests merged in 2024-02, with the labels that each got.

#6018 chore: update license-checker to 1.12.6 (CP 24.3)
  vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/pom.xml
Labels: target/23.3, target/24.2, target/23.4, target/14.11, target/22.2

#6019 fix: refresh value on data communicator reset
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxSelectedItemsOnTopPage.java
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxSelectedItemsOnTopIT.java
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxDataController.java
Labels: target/24.3

#6028 fix: do not defer updating client-side selection mode
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/DetachReattachPage.java
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DetachReattachIT.java
  vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Labels: target/24.3

#6030 fix: do not defer updating client-side sorter directions
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DetachReattachIT.java
  vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Labels: target/24.3

#6032 chore: upgrade license-checker to 1.12.7
  vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/pom.xml
Labels: target/23.3, target/24.2, target/23.4, target/24.3

#6050 chore: upgrade testbench to 8.2.6
  pom.xml
Labels: target/23.4

#6059 chore: upgrade license-checker to 1.12.8
  vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/pom.xml
Labels: target/23.3, target/24.2, target/23.4, target/24.3

#6068 feat: allow using live directive in LitRenderer
  vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/src/main/java/com/vaadin/flow/data/renderer/tests/LitRendererPage.java
  vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/src/test/java/com/vaadin/flow/data/renderer/tests/LitRendererIT.java
  vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/resources/META-INF/resources/frontend/lit-renderer.ts
Labels: target/24.3

#6010 fix: sanitize last requested range on clear
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/grid-connector.test.ts
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/test/shared.ts
  vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts
Labels: target/24.3

#6077 test: fix flaky menubar ITs
  vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/src/test/java/com/vaadin/flow/component/menubar/tests/MenuBarPageIT.java
Labels: target/23.4

#6082 fix: allow short formats, add date-picker connector WTR tests
  .gitignore
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/test/date-picker-connector.test.ts
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/test/env-setup.ts
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/test/shared.ts
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/web-test-runner.config.mjs
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js
Labels: target/24.3
