Repository vaadin/flow-components, pull requests merged in 2024-06, with the labels that each got.

#6339 fix: run grid dnd filters on dropmode and draggable change
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/DragAndDropGridIT.java
  vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Labels: target/23.4, target/24.3, target/14.11, target/23.5, target/24.4

#6347 fix: make setRequired also activate required validation
  vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/validation/NumberFieldBasicValidationPage.java
  vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/AbstractNumberField.java
  vaadin-text-field-flow-parent/vaadin-text-field-flow/src/main/java/com/vaadin/flow/component/textfield/TextFieldBase.java
Labels: target/24.3, target/24.4

#6380 chore: upgrade to TB 9.3.1
  pom.xml
Labels: target/24.4
