Repository vaadin/flow-components, pull requests merged in 2024-08, with the labels that each got.

#6510 test: replace flaky IT with unit test
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxCustomValuePage.java
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxCustomValueIT.java
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/MultiSelectComboBoxFilteringTest.java
Labels: target/23.4, target/24.3, target/23.5, target/24.4

#6515 test: replace flaky IT with unit test (#6510) (CP: 23.5)
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxCustomValuePage.java
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/MultiSelectComboBoxCustomValueIT.java
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/test/java/com/vaadin/flow/component/combobox/MultiSelectComboBoxFilteringTest.java
Labels: target/23.4

#6512 chore: replace formatter with spotless [skip ci]
  README.md
  pom.xml
  vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetJsniUtil.java
  vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/client/ApplicationConfiguration.java
Labels: target/23.4, target/24.3, target/23.5, target/24.4

#6502 refactor: use native label in formitem instead of deprecated label
  vaadin-form-layout-flow-parent/vaadin-form-layout-flow/src/main/java/com/vaadin/flow/component/formlayout/FormLayout.java
Labels: target/24.3, target/24.4

#6543 fix: warn and revert to prev index when selecting invalid index
  vaadin-tabs-flow-parent/vaadin-tabs-flow/src/main/java/com/vaadin/flow/component/tabs/Tabs.java
  vaadin-tabs-flow-parent/vaadin-tabs-flow/src/test/java/com/vaadin/flow/component/tabs/tests/TabsTest.java
Labels: target/24.3, target/24.4

#6571 fix: make radio button group with size request serializable
  vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
  vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/test/java/com/vaadin/flow/component/radiobutton/tests/RadioButtonSerializableTest.java
Labels: target/24.3, target/23.5, target/24.4
