Repository vaadin/flow-components, pull requests merged in 2024-12, with the labels that each got.

#6896 docs: use correct Popover delay default values in JavaDoc
  vaadin-popover-flow-parent/vaadin-popover-flow/src/main/java/com/vaadin/flow/component/popover/Popover.java
Labels: target/24.5, target/24.6

#6900 docs: fix incorrect getOffset() usage in ComboBox JavaDoc
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow/src/main/java/com/vaadin/flow/component/combobox/ComboBoxBase.java
Labels: target/24.5, target/24.6

#6904 fix: make waitForUploads poll for upload processing until completion or timeout
  vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/UploadIT.java
  vaadin-upload-flow-parent/vaadin-upload-testbench/src/main/java/com/vaadin/flow/component/upload/testbench/UploadElement.java
Labels: target/24.5, target/24.6

#6910 chore: TestBench 9.3.7
  pom.xml
Labels: target/24.5, target/24.6

#6917 test: use textContent property in side nav i18n tests
  vaadin-side-nav-flow-parent/vaadin-side-nav-flow-integration-tests/src/test/java/com/vaadin/flow/component/sidenav/tests/SideNavI18NIT.java
Labels: target/24.5

#6918 test: use Enter to commit custom values
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/validation/MultiSelectComboBoxBasicValidationIT.java
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/validation/MultiSelectComboBoxBinderValidationIT.java
Labels: target/23.5, target/24.4, target/24.5

#6922 fix: ensure that invalid state is set from the server
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/main/java/com/vaadin/flow/component/combobox/test/validation/ComboBoxInitialValueValidationPage.java
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/src/test/java/com/vaadin/flow/component/combobox/test/validation/ComboBoxInitialValueValidationIT.java
  vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/ClientValidationUtil.java
Labels: target/24.5, target/24.6

#6933 fix: update keymapper when refreshing select item
  vaadin-select-flow-parent/vaadin-select-flow/src/main/java/com/vaadin/flow/component/select/Select.java
  vaadin-select-flow-parent/vaadin-select-flow/src/test/java/com/vaadin/flow/component/select/SelectTest.java
Labels: target/24.5, target/24.6

#6934 fix: update keymapper when refreshing radio button item
  vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/main/java/com/vaadin/flow/component/radiobutton/RadioButtonGroup.java
  vaadin-radio-button-flow-parent/vaadin-radio-button-flow/src/test/java/com/vaadin/flow/component/radiobutton/RadioButtonGroupTest.java
Labels: target/24.5, target/24.6

#6935 fix: update keymapper when refreshing checkbox item
  vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/main/java/com/vaadin/flow/component/checkbox/CheckboxGroup.java
  vaadin-checkbox-flow-parent/vaadin-checkbox-flow/src/test/java/com/vaadin/flow/component/checkbox/tests/CheckboxGroupTest.java
Labels: target/24.5, target/24.6

#6947 fix: restore i18n when detaching and reattaching
  vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/main/java/com/vaadin/flow/component/richtexteditor/tests/RichTextEditorI18nPage.java
  vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/src/test/java/com/vaadin/flow/component/richtexteditor/tests/RichTextEditorI18nIT.java
  vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java
Labels: target/24.5, target/24.6

#6936 fix: ComboBoxElement#clear to empty the field as well
  vaadin-combo-box-flow-parent/vaadin-combo-box-testbench/src/main/java/com/vaadin/flow/component/combobox/testbench/ComboBoxElement.java
Labels: target/24.5, target/24.6

#6964 fix: update panes positions on Spreadsheet resize
  vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SheetWidget.java
  vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/main/java/com/vaadin/flow/component/spreadsheet/tests/SizingPage.java
  vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/SizingIT.java
Labels: target/24.5, target/24.6

#6966 test: refactor DatePickerIT to use TestBench API
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/src/test/java/com/vaadin/flow/component/datepicker/DatePickerIT.java
Labels: target/24.5, target/24.6

#6983 chore: format JS in connectors and integration tests with Prettier
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/resources/META-INF/resources/frontend/datepickerConnector.js
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/frontend/src/grid-on-client-and-slot.js
  vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts
  vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/vaadin-grid-flow-selection-column.js
  vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow-integration-tests/frontend/src/ImplicitLumoThemedTemplate.js
  vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow-integration-tests/frontend/theme/lumo/ImplicitLumoThemedTemplate.js
  vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow-integration-tests/frontend/theme/lumo/LumoThemedTemplate.js
  vaadin-material-theme-flow-parent/vaadin-material-theme-flow-integration-tests/frontend/src/MaterialThemedTemplate.js
  vaadin-material-theme-flow-parent/vaadin-material-theme-flow-integration-tests/frontend/src/NotThemedTemplate.js
  vaadin-material-theme-flow-parent/vaadin-material-theme-flow-integration-tests/frontend/theme/lumo/MaterialThemedTemplate.js
  vaadin-material-theme-flow-parent/vaadin-material-theme-flow-integration-tests/frontend/theme/material/MaterialThemedTemplate.js
Labels: target/24.5, target/24.6

#6986 chore: add lint-staged to run prettier on git commit
  .husky/pre-commit
  package.json
Labels: target/24.5, target/24.6

#6982 fix: prevent client updates when handling events from client
  vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/main/java/com/vaadin/flow/component/dashboard/Dashboard.java
  vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/DashboardItemMoveTest.java
  vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/DashboardItemResizeTest.java
  vaadin-dashboard-flow-parent/vaadin-dashboard-flow/src/test/java/com/vaadin/flow/component/dashboard/DashboardTest.java
Labels: target/24.6
