Repository vaadin/flow-components, pull requests merged in 2024-05, with the labels that each got.

#4594 feat!: allow changing the icon
  vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/Icon.java
  vaadin-icons-flow-parent/vaadin-icons-flow/src/test/java/com/vaadin/flow/component/icon/tests/IconTest.java
Labels: target/24.4

#6288 remove non-exist entry in versions.json [skip ci]
  scripts/updatePlatform.js
Labels: target/24.4

#6292 Revert "remove non-exist entry in versions.json [skip ci] (#6288)" [skip ci]
  scripts/updatePlatform.js
Labels: target/24.4

#6276 feat: add HasLabelAsText interface to ButtonElement
  vaadin-button-flow-parent/vaadin-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/button/tests/ButtonIT.java
  vaadin-button-flow-parent/vaadin-button-testbench/src/main/java/com/vaadin/flow/component/button/testbench/ButtonElement.java
  vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/main/java/com/vaadin/flow/component/textfield/tests/TextFieldPage.java
  vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/src/test/java/com/vaadin/flow/component/textfield/tests/TextFieldPageIT.java
Labels: enhancement, testbench

#6253 fix: set maxFiles to Infinity when setting a MultiFileReceiver
  vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/main/java/com/vaadin/flow/component/upload/tests/SwitchReceiversPage.java
  vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/src/test/java/com/vaadin/flow/component/upload/tests/SwitchReceiversIT.java
  vaadin-upload-flow-parent/vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java
  vaadin-upload-flow-parent/vaadin-upload-flow/src/test/java/com/vaadin/flow/component/upload/tests/UploadTest.java
Labels: target/24.3, target/24.4

#6317 docs: add note about 'em' unit on Column#setWidth javadoc
  vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Labels: target/24.3, target/24.4
