Repository vaadin/flow-components, pull requests merged in 2025-01, with the labels that each got.

#7000 fix: dispatch change event in setChecked
  vaadin-checkbox-flow-parent/vaadin-checkbox-testbench/src/main/java/com/vaadin/flow/component/checkbox/testbench/CheckboxElement.java
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridMultiSelectionColumnPageIT.java
Labels: target/24.6

#7006 test: update loginform element to use part names
  vaadin-login-flow-parent/vaadin-login-testbench/src/main/java/com/vaadin/flow/component/login/testbench/LoginFormElement.java
Labels: target/24.5

#7010 chore: Sync eclipse formatting file with Flow
  eclipse/VaadinJavaConventions.xml
  vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/ChartVariant.java
  vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/events/HasItem.java
  vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/AxisType.java
  vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/DashStyle.java
  vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/ExportFileType.java
  vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/FlagShape.java
  vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/MarkerSymbolEnum.java
  vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/RangeSelectorTimespan.java
  vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/Shape.java
  vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/TimeUnit.java
  vaadin-charts-flow-parent/vaadin-charts-flow/src/main/java/com/vaadin/flow/component/charts/model/TreeMapLayoutAlgorithm.java
  vaadin-custom-field-flow-parent/vaadin-custom-field-flow/src/main/java/com/vaadin/flow/component/customfield/CustomFieldVariant.java
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/data/bean/Country.java
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/data/bean/UsaState.java
  vaadin-icons-flow-parent/vaadin-icons-flow/src/main/java/com/vaadin/flow/component/icon/VaadinIcon.java
  vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow/src/main/java/com/vaadin/flow/theme/lumo/LumoIcon.java
  vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/Notification.java
  vaadin-notification-flow-parent/vaadin-notification-flow/src/main/java/com/vaadin/flow/component/notification/NotificationVariant.java
  vaadin-renderer-flow-parent/vaadin-renderer-flow/src/main/java/com/vaadin/flow/data/renderer/LitRenderer.java
  vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/test/java/com/vaadin/flow/component/sidenav/tests/SideNavTest.java
  vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/main/java/com/vaadin/flow/component/spreadsheet/tests/fixtures/SimpleCustomEditorFixture.java
  vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/main/java/com/vaadin/flow/component/spreadsheet/tests/fixtures/TestFixtures.java
  vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/src/main/java/com/vaadin/flow/component/spreadsheet/SpreadsheetStyleFactory.java
  vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerTest.java
Labels: target/23.5, target/24.5, target/24.6

#7029 chore: add shared Vite config
  shared/shared-vite-config.ts
  shared/web-components-vite-plugin.ts
  vaadin-accordion-flow-parent/vaadin-accordion-flow-integration-tests/vite.config.ts
  vaadin-app-layout-flow-parent/vaadin-app-layout-flow-integration-tests/vite.config.ts
  vaadin-avatar-flow-parent/vaadin-avatar-flow-integration-tests/vite.config.ts
  vaadin-board-flow-parent/vaadin-board-flow-integration-tests/vite.config.ts
  vaadin-button-flow-parent/vaadin-button-flow-integration-tests/vite.config.ts
  vaadin-card-flow-parent/vaadin-card-flow-integration-tests/vite.config.ts
  vaadin-charts-flow-parent/vaadin-charts-flow-integration-tests/vite.config.ts
  vaadin-checkbox-flow-parent/vaadin-checkbox-flow-integration-tests/vite.config.ts
  vaadin-combo-box-flow-parent/vaadin-combo-box-flow-integration-tests/vite.config.ts
  vaadin-confirm-dialog-flow-parent/vaadin-confirm-dialog-flow-integration-tests/vite.config.ts
  vaadin-context-menu-flow-parent/vaadin-context-menu-flow-integration-tests/vite.config.ts
  vaadin-cookie-consent-flow-parent/vaadin-cookie-consent-flow-integration-tests/vite.config.ts
  vaadin-crud-flow-parent/vaadin-crud-flow-integration-tests/vite.config.ts
  vaadin-custom-field-flow-parent/vaadin-custom-field-flow-integration-tests/vite.config.ts
  vaadin-dashboard-flow-parent/vaadin-dashboard-flow-integration-tests/vite.config.ts
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow-integration-tests/vite.config.ts
  vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow-integration-tests/vite.config.ts
  vaadin-details-flow-parent/vaadin-details-flow-integration-tests/vite.config.ts
  vaadin-dialog-flow-parent/vaadin-dialog-flow-integration-tests/vite.config.ts
  vaadin-field-highlighter-flow-parent/vaadin-field-highlighter-flow-integration-tests/vite.config.ts
  vaadin-form-layout-flow-parent/vaadin-form-layout-flow-integration-tests/vite.config.ts
  vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/vite.config.ts
  vaadin-icons-flow-parent/vaadin-icons-flow-integration-tests/vite.config.ts
  vaadin-list-box-flow-parent/vaadin-list-box-flow-integration-tests/vite.config.ts
  vaadin-login-flow-parent/vaadin-login-flow-integration-tests/vite.config.ts
  vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow-integration-tests/vite.config.ts
  vaadin-map-flow-parent/vaadin-map-flow-integration-tests/vite.config.ts
  vaadin-material-theme-flow-parent/vaadin-material-theme-flow-integration-tests/vite.config.ts
  vaadin-menu-bar-flow-parent/vaadin-menu-bar-flow-integration-tests/vite.config.ts
  vaadin-messages-flow-parent/vaadin-messages-flow-integration-tests/vite.config.ts
  vaadin-notification-flow-parent/vaadin-notification-flow-integration-tests/vite.config.ts
  vaadin-ordered-layout-flow-parent/vaadin-ordered-layout-flow-integration-tests/vite.config.ts
  vaadin-popover-flow-parent/vaadin-popover-flow-integration-tests/vite.config.ts
  vaadin-progress-bar-flow-parent/vaadin-progress-bar-flow-integration-tests/vite.config.ts
  vaadin-radio-button-flow-parent/vaadin-radio-button-flow-integration-tests/vite.config.ts
  vaadin-renderer-flow-parent/vaadin-renderer-flow-integration-tests/vite.config.ts
  vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow-integration-tests/vite.config.ts
  vaadin-select-flow-parent/vaadin-select-flow-integration-tests/vite.config.ts
  vaadin-side-nav-flow-parent/vaadin-side-nav-flow-integration-tests/vite.config.ts
  vaadin-split-layout-flow-parent/vaadin-split-layout-flow-integration-tests/vite.config.ts
  vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/vite.config.ts
  vaadin-tabs-flow-parent/vaadin-tabs-flow-integration-tests/vite.config.ts
  vaadin-text-field-flow-parent/vaadin-text-field-flow-integration-tests/vite.config.ts
  vaadin-time-picker-flow-parent/vaadin-time-picker-flow-integration-tests/vite.config.ts
  vaadin-upload-flow-parent/vaadin-upload-flow-integration-tests/vite.config.ts
  vaadin-virtual-list-flow-parent/vaadin-virtual-list-flow-integration-tests/vite.config.ts
Labels: target/24.5, target/24.6

#7030 fix: prevent initialValue from becoming emptyValue
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/main/java/com/vaadin/flow/component/datepicker/DatePicker.java
  vaadin-date-picker-flow-parent/vaadin-date-picker-flow/src/test/java/com/vaadin/flow/component/datepicker/DatePickerTest.java
  vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java
  vaadin-time-picker-flow-parent/vaadin-time-picker-flow/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerTest.java
Labels: target/24.5, target/24.6

#7038 fix: fix typo in Lumo utility align-start class names
  vaadin-lumo-theme-flow-parent/vaadin-lumo-theme-flow/src/main/java/com/vaadin/flow/theme/lumo/LumoUtility.java
Labels: target/24.4, target/24.5, target/24.6

#7045 fix: replace requestAnimationFrame with global click listener
  vaadin-button-flow-parent/vaadin-button-flow-integration-tests/src/test/java/com/vaadin/flow/component/button/tests/ButtonIT.java
  vaadin-context-menu-flow-parent/vaadin-context-menu-flow-integration-tests/src/test/java/com/vaadin/flow/component/contextmenu/it/MenuItemDisableOnClickIT.java
  vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/java/com/vaadin/flow/component/shared/internal/DisableOnClickController.java
  vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/main/resources/META-INF/resources/frontend/disableOnClickFunctions.js
  vaadin-flow-components-shared-parent/vaadin-flow-components-base/src/test/java/com/vaadin/flow/component/shared/DisableOnClickControllerTest.java
Labels: target/24.6

#6973 fix: hide cell content until value is updated
  vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/java/com/vaadin/flow/component/gridpro/GridPro.java
  vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/resources/META-INF/resources/frontend/gridProConnector.js
Labels: target/24.5, target/24.6

#7074 fix: ensure invalid state is correctly set on slotted pickers
  vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/main/java/com/vaadin/flow/component/datetimepicker/DateTimePicker.java
  vaadin-date-time-picker-flow-parent/vaadin-date-time-picker-flow/src/test/java/com/vaadin/flow/component/datetimepicker/validation/BasicValidationTest.java
Labels: target/24.5, target/24.6
