Repository vaadin/flow-components, pull requests merged in 2025-08, with the labels that each got.

#7747 chore: upgrade TB to 9.4.2
  pom.xml
Labels: target/24.9

#7803 chore: upgrade testbench 9.4.3
  pom.xml
Labels: target/24.8

#7817 chore: upgrade license-checker to 2.0.0-alpha1
  vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/ContextMenuIT.java
  vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/pom.xml
Labels: target/24.9, cherry-picked-24.9

#7847 fix: determine whether a cell is locked on the fly
  vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SelectionHandler.java
  vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-client/src/main/java/com/vaadin/addon/spreadsheet/client/SpreadsheetWidget.java
  vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/main/java/com/vaadin/flow/component/spreadsheet/tests/LockedCellsWithCustomEditorPage.java
  vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/main/resources/test_sheets/locked_cell_next_to_custom_editor.xlsx
  vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow-integration-tests/src/test/java/com/vaadin/flow/component/spreadsheet/test/LockedCellsWithCustomEditorIT.java
Labels: target/24.8, target/24.9

#7849 feat: Tooltip support for SideNavItem
  vaadin-side-nav-flow-parent/vaadin-side-nav-flow-integration-tests/src/main/java/com/vaadin/flow/component/sidenav/tests/SideNavPage.java
  vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/main/java/com/vaadin/flow/component/sidenav/SideNavItem.java
  vaadin-side-nav-flow-parent/vaadin-side-nav-flow/src/test/java/com/vaadin/flow/component/sidenav/tests/SideNavItemTest.java
Labels: target/24.9

#7903 chore: Update license-checker version to 2.0.0-beta1
  vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-flow/pom.xml
Labels: target/24.9

#7915 chore: update TB to 9.4.4 (24.9)
  pom.xml
  vaadin-spreadsheet-flow-parent/vaadin-spreadsheet-testbench/src/main/java/com/vaadin/flow/component/spreadsheet/testbench/SpreadsheetElement.java
Labels: target/24.8
