Repository vaadin/flow-components, pull requests merged in 2025-02, with the labels that each got.

#7079 fix: ignore row details cells when applying cell update animation
  vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/main/java/com/vaadin/flow/component/gridpro/tests/GridProItemDetailsPage.java
  vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow-integration-tests/src/test/java/com/vaadin/flow/component/gridpro/tests/GridProItemDetailsIT.java
  vaadin-grid-pro-flow-parent/vaadin-grid-pro-flow/src/main/resources/META-INF/resources/frontend/gridProConnector.js
Labels: target/24.5, target/24.6

#7082 chore: improve license header formatting
  scripts/templates/apache2-license-header.txt
  scripts/templates/vaadin-commercial-license-header.txt
Labels: target/23.5, target/14.12, target/24.5, target/24.6

#7088 chore: improve license header formatting (#7082) (CP: 24.6)
  scripts/templates/apache2-license-header.txt
  scripts/templates/vaadin-commercial-license-header.txt
Labels: target/23.5, target/14.12, target/24.5

#7110 fix: Use correct formatting for logging
  vaadin-grid-flow-parent/vaadin-grid-flow/src/main/java/com/vaadin/flow/component/grid/Grid.java
Labels: target/24.6

#7131 fix: check wether HTML values contains user content
  vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/main/java/com/vaadin/flow/component/richtexteditor/RichTextEditor.java
  vaadin-rich-text-editor-flow-parent/vaadin-rich-text-editor-flow/src/test/java/com/vaadin/flow/component/richtexteditor/RichTextEditorHtmlIsEmptyTest.java
Labels: target/24.6

#7155 fix: remove size reset to allow data provider calls to resolve
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/main/java/com/vaadin/flow/component/grid/it/GridUpdateDataProviderPage.java
  vaadin-grid-flow-parent/vaadin-grid-flow-integration-tests/src/test/java/com/vaadin/flow/component/grid/it/GridUpdateDataProviderIT.java
  vaadin-grid-flow-parent/vaadin-grid-flow/src/main/resources/META-INF/resources/frontend/gridConnector.ts
Labels: target/24.6, target/24.7
